name: aloha
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pytorch=2.0.0
  - torchvision
  - pytorch-cuda=12.1
  - pyquaternion
  - pyyaml
  - rospkg
  - pexpect
  - mujoco
  - dm_control
  - py-opencv
  - matplotlib
  - einops
  - packaging
  - h5py
  - ipython
